version: 2
jobs:
  build:
    docker:
      - image: circleci/node:alpine
    steps:
      - checkout
      - run: yarn build:all
  build-workspace-a:
    docker:
      - image: circleci/node:alpine
    steps:
      - checkout
      - run: yarn build:workspace-a
  test:
    docker:
      - image: circleci/node:alpine
    steps:
      - checkout
      - run: yarn test:all
  deploy:
    docker:
      - image: circleci/node:alpine
    steps:
      - checkout
      - run: yarn deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  workspace-a:
    jobs:
      - build-workspace-a:
          filters:
            branches:
              only: /workspace-a/